#!/usr/bin/perl -w

use strict;
use File::Find;

# get locale (for Name[*])

my $lang4="";
$lang4=$ENV{LANG} if exists $ENV{LANG};
$lang4=$ENV{LC_MESSAGES} if exists $ENV{LC_MESSAGES};
$lang4=$ENV{LC_ALL} if exists $ENV{LC_ALL};
my $lang3=$lang4;
$lang3=~s/@.*//;
my $lang2=$lang3;
$lang2=~s/\..*//;
my $lang1=$lang2;
$lang1=~s/_.*//;

# read desktop entries TODO: DESKTOP_FILE_PATH

my %apps;

my $ae=1;	# application exec
my $ai=2;	# application icon
find(\&wanted,'/usr/share/applications/');

sub wanted {
	return if (!-f || /^\./ || !/\.desktop$/);
	my $name="";
	my $exec="";
	my $icon="";
	my $cats="";
	my $term=0;
	my $lang=0;
	open F_IN, "$_" or warn "! Cannot open $_: $!\n" and return;
	while(<F_IN>) {
		if (/^Name=(.+)/ && $lang<1) {
			$name=$1;
		}
		if (/^Name\[$lang1\]=(.+)/ && $lang<2) {
			$name=$1;
			$lang=1;
		}
		if (/^Name\[$lang2\]=(.+)/ && $lang<3) {
			$name=$1;
			$lang=2;
		}
		if (/^Name=\[$lang3\](.+)/ && $lang<4) {
			$name=$1;
			$lang=3;
		}
		if (/^Name=\[$lang4\](.+)/ && $lang<5) {
			$name=$1;
			$lang=4;
		}
		$exec=$1 if /^Exec=(.+)/;
		$icon=$1 if /^Icon=(.+)/;
		$cats=$1 if /^Categories=(.+)/;
		$term=1 if /^Terminal=1/;
	}
	close F_IN;
	$exec="xterm -e $exec" if $term==1;
	my @cats=split(/;+/,$cats);
	my $cat;
	foreach $cat(@cats) {
# TODO: check if binary exist within $PATH
		$apps{$cat}{$name}[$ae]="$exec";
# TODO: check if icon exist
		$apps{$cat}{$name}[$ai]="$icon";
	}
}

=for comment print apps
foreach my $category(sort keys %apps) {
	print "$category	\n";
	foreach my $name(sort keys %{$apps{$category}}) {
		printf "	%s|%s|%s\n",$name,$apps{$category}{$name}[$ai],$apps{$category}{$name}[$ae];
	}
	print "\n";
}
=cut

# read XDG menu specification

my $file="";

#open F_IN, "/etc/xdg/menus/applications.menu" or die "! Cannot open $_: $!\n";
open F_IN, "/home/gotar/xdg/menus/applications.menu" or die "! Cannot open $_: $!\n";
#open F_IN, "/home/gotar/xdg/menus/kde-settings.menu" or die "! Cannot open $_: $!\n";
while(<F_IN>) {
	#s/\s*//g;
	chop;
	$file.=$_;
}
close F_IN;

sub gettag {
	$file=~s/.*?<(.*?)>\s*//;
	$1;
}

sub getname {
	$file=~s/\s*(.*?)\s*<//;
	$file="<".$file;
	$1;
}

my @menu;
		# positive level: submenu
		# negative level: entry
		my $ml=0;
		my $mi=1;
		my $me=2;
=for menustruct
	menu[x] {ble}	-1	ble.png	/usr/bin/ble
		{bla}	3	bla.xpm
		{foo}	5	foo.png
		{bar}	7	bar.xpm

test example:

$menu[0]{zadad}[0]=-1;
$menu[0]{zadad}[1]="foobar.png";
$menu[0]{zadad}[2]="/foo/bar/tralala";
$menu[0]{dad}[0]=1;
$menu[0]{dad}[1]="bar.png";
$menu[1]{dcd}[0]=-1;
$menu[1]{dcd}[1]="foo.png";
$menu[1]{dcd}[2]="/foo/tralala";
=cut

my $level=0;
my $mno=0;	# menu number
my $trigger=0;
my $tag;
my @name;
my @directory;
my @include;
#my %tmpapps;
my @menustack;

sub cand {
}

sub cor {
}

sub cnot {
}

$#menu++;	# let's start from index 1
		# this index is a pointer to menu struct
		# (entry in $menu[] table) via $mno
		# 0 means empty, so it's ommited
		# twill be made choosable

while($trigger==0 || $level>0) {
	$tag=&gettag;
	if($tag=~/^menu$/i) {
		$level++;
		$#menu++;
		$menustack[$#menustack+1]=$mno;
		$mno=$#menu;
		#$name[$level]="";
		#$directory[$level]="";
		#$include[$level]=0;
		$trigger=1;
		next;
	}
	if($tag=~/^\/menu$/i) {
		$mno=$menustack[$#menustack];
		$#menustack--;
		$level--;
		next;
	}
	if($tag=~/^name$/i) {	# TODO: search forward for it
		$name[$level]=&getname;
		$menu[$menustack[$#menustack]]{$name[$level]}[$ml]=$mno;
		#$menu[$#menu]{$name[$level]}[$ml]=$level;
#		$menu[$#menu+1][$ml]=$level;
#		$menu[$#menu][$mn]=$name[$level];
		&gettag;		# must be </name> else GIGO and we don't care
		next;
	}
	if($tag=~/^\/name$/i) {
		# we shouldn't be here!
		next;
	}
	if($tag=~/^directory$/i) {	# TODO: search forward for it
		$directory[$level]=&getname;
		&gettag;		# must be </directory> else GIGO and we don't care
		next;
	}
	if($tag=~/^\/directory$/i) {
		# we shouldn't be here!
		next;
	}
	if($tag=~/^include$/i) {
		$include[$level]=1;
		next;
	}
	if($tag=~/^\/include$/i) {
		$include[$level]=0;
		next;
	}
	if(($tag=~/^and$/i)&&($include[$level])) {
		&cand;
		next;
	}
	if(($tag=~/^\/and$/i)&&($include[$level])) {
		# we shouldn't be here!
		next;
	}
	if(($tag=~/^or$/i)&&($include[$level])) {
		&cor;
		next;
	}
	if(($tag=~/^\/or$/i)&&($include[$level])) {
		# we shouldn't be here!
		next;
	}
	if(($tag=~/^not$/i)&&($include[$level])) {
		&cnot;
		next;
	}
	if(($tag=~/^\/not$/i)&&($include[$level])) {
		# we shouldn't be here!
		next;
	}
	if(($tag=~/^category$/i)&&($include[$level])) {
		$directory[$level]=&getname;
		foreach my $name(sort keys %{$apps{$directory[$level]}}) {
			$menu[$mno]{$name}[$ml]=-1;
			$menu[$mno]{$name}[$mi]=$apps{$directory[$level]}{$name}[$ai];
			$menu[$mno]{$name}[$me]=$apps{$directory[$level]}{$name}[$ae];
		}
		&gettag;		# must be </category> else GIGO and we don't care
		next;
	}
	if(($tag=~/^\/category$/i)&&($include[$level])) {
		# we shouldn't be here!
		next;
	}
	# print "$level: $tag\n";
}

# print "\n\n\n$file\n";

$level=-1;
sub outgen {
	my $no=$_[0];
	foreach my $entry(sort keys %{$menu[$no]}) {
		next if $menu[$no]{$entry}[$ml]==0;
		if($menu[$no]{$entry}[$ml]<0) {
			for(my $i=0; $i<=$level; $i++) {
				print "	";
			}
			print "Entry: \"$entry\" $menu[$no]{$entry}[$mi] $menu[$no]{$entry}[$me]\n";
		} else {
			for(my $i=0; $i<=$level; $i++) {
				print "	";
			}
			print "Menu: \"$entry\" $menu[$no]{$entry}[$mi]\n";
			$level++;
			outgen($menu[$no]{$entry}[$ml]);
			$level--;
		}
	}
}

&outgen(0);
